name: ShulkerPacks
version: 1.4.8
main: me.darkolythe.shulkerpacks.ShulkerPacks
api-version: 1.13

permissions:
  shulkerpacks.use:
    description: gives player permission to open shulker boxes in their inventory
    default: op